# Lecture Notes Per Week

::: callout-important
Be visiting the webpage every week for lecture notes.

They will uploaded here each week or earlier as it may be necessary.
:::

## Week One Lecture

Download or view: [Week One](/sta2454/Week_One.pdf).

## Week Two Lecture

Download or view: [Week Two](/sta454/Week_Two.pdf).

## Week Three Lecture

Download or view: [Week Three](/sta2454/Week_Three.pdf).

## Week Four Lecture

Download or view: [Week Four](/sta2454/Week_Four.pdf).

## Week Five Lecture

CAT 1 as per the University Plan

## Week Six Lecture

Download or view: [Week Six](/sta2270/Week_Six.pdf).

## Week Seven Lecture

Download or view: [Week Seven](/sta2454/Week_Seven.pdf).

## Week Eight Lecture

Download or view: [Week Eight](/sta2454/Week_Eight.pdf).

## Week Nine Lecture

CAT 2 Revision

## Week Ten

CAT 2 as per University Plan

## Week Eleven Lecture

Group Project Preparations


## Week Twelve 

Group Project Presentations

## Week 13 and 14

Revision for Examinations
